# (14) GRA — tables (language)


project = ```GRA```, host = ```any```, device = ```any```

In [1]:
# HIDE CODE


import os, pathlib
from IPython.display import display

# tmp & extras dir
_jb_dir = pathlib.Path(os.environ['HOME'])
_jb_dir /= 'Dropbox/git/jb-progress-2026'
extras_dir = _jb_dir / '_extras'
fig_base_dir = _jb_dir / 'figs'
tmp_dir = _jb_dir / 'tmp'

# GitHub 
from gra.utils.plotting import *

# warnings, tqdm, & style
warnings.filterwarnings('ignore', category=DeprecationWarning)
warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)
from rich.jupyter import print
%matplotlib inline
set_style()

In [2]:
from gra.experiments.wandb_analysis import *


df = fetch_runs(entity='pal-lab', project='GRA-fineweb-edu-10B')
summary = get_optimizer_summary(df)  # aggregates across seeds
# best_per_opt = compare_optimizers(df, metric='best_val_acc')

wandb: ERROR Failed to detect the name of this notebook. You can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: hadivafaii (poisson-collab) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

Fetching runs from: pal-lab/GRA-fineweb-edu-10B
Found 22 runs
Processed 20 runs (after filtering)

In [4]:
summary = summary.sort_values(
    by="eval/best_val_loss_mean",
    ascending=True,
    na_position="last",
).reset_index(drop=True)

In [5]:
summary

,optimizer,learning_rate,beta1,beta2,mass,eval/best_val_loss_mean,eval/best_val_loss_std,eval/best_val_loss_count,eval/val_loss_mean,eval/val_loss_std,eval/val_loss_count,eval/train_loss_mean,eval/train_loss_std,eval/train_loss_count,train/max_grad_mean,train/max_grad_std,train/max_grad_count,train/grad_sparsity_mean,train/grad_sparsity_std,train/grad_sparsity_count
0,rel_lion,0.0010,0.95,0.990,0.0100,3.298597,NaN,1,3.298597,NaN,1,3.300747,NaN,1,0.064554,NaN,1,0.298314,NaN,1
1,rel_lion,0.0010,0.95,0.990,0.0010,3.300188,NaN,1,3.300188,NaN,1,3.302549,NaN,1,0.109107,NaN,1,0.303766,NaN,1
2,rel_lion,0.0010,0.95,0.990,0.0000,3.300351,NaN,1,3.300351,NaN,1,3.302734,NaN,1,0.031839,NaN,1,0.304160,NaN,1
3,rel_lion,0.0010,0.95,0.990,0.0001,3.300793,NaN,1,3.300793,NaN,1,3.302801,NaN,1,0.162902,NaN,1,0.304657,NaN,1
4,rel_lion,0.0010,0.95,0.990,0.1000,3.304492,NaN,1,3.304492,NaN,1,3.307053,NaN,1,0.024359,NaN,1,0.283727,NaN,1
5,rel_lion,0.0030,0.95,0.990,0.1000,3.307118,NaN,1,3.307118,NaN,1,3.309850,NaN,1,0.026068,NaN,1,0.285564,NaN,1
6,lion,0.0010,0.90,0.990,0.1000,3.309639,NaN,1,3.309639,NaN,1,3.311647,NaN,1,0.022530,NaN,1,0.286176,NaN,1
7,rel_lion,0.0005,0.95,0.990,0.1000,3.309824,NaN,1,3.309824,NaN,1,3.311668,NaN,1,0.070987,NaN,1,0.282538,NaN,1
8,adamw,0.0030,0.99,0.990,0.1000,3.317532,NaN,1,3.317532,NaN,1,3.320191,NaN,1,0.022705,NaN,1,0.276948,NaN,1
9,lion,0.0005,0.90,0.990,0.1000,3.317696,NaN,1,3.317696,NaN,1,3.319554,NaN,1,0.022575,NaN,1,0.281735,NaN,1
10,rel_lion,0.0010,0.95,0.990,1.0000,3.317761,NaN,1,3.317761,NaN,1,3.320150,NaN,1,0.039484,NaN,1,0.269874,NaN,1
11,rel_lion,0.0005,0.95,0.990,1.0000,3.323762,NaN,1,3.323762,NaN,1,3.325949,NaN,1,0.033641,NaN,1,0.269808,NaN,1
12,rel_lion,0.0080,0.95,0.990,0.1000,3.330405,NaN,1,3.330405,NaN,1,3.334327,NaN,1,0.013415,NaN,1,0.288443,NaN,1
13,rel_lion,0.0010,0.95,0.950,0.1000,3.338319,NaN,1,3.338319,NaN,1,3.340455,NaN,1,0.020459,NaN,1,0.275338,NaN,1
14,rel_signum,0.0030,0.95,0.950,0.1000,3.343594,NaN,1,3.343594,NaN,1,3.346306,NaN,1,0.022361,NaN,1,0.273650,NaN,1
15,rel_lion,0.0001,0.90,0.990,0.0010,3.353424,NaN,1,3.353424,NaN,1,3.354988,NaN,1,0.019531,NaN,1,0.273729,NaN,1
16,lion,0.0001,0.90,0.990,0.1000,3.353702,NaN,1,3.353702,NaN,1,3.355271,NaN,1,0.020142,NaN,1,0.273543,NaN,1
17,rel_lion,0.0010,0.80,0.999,0.1000,3.378918,NaN,1,3.378918,NaN,1,3.380648,NaN,1,0.024292,NaN,1,0.272051,NaN,1
18,rel_lion,0.0010,0.50,0.990,1.0000,3.797948,NaN,1,3.800384,NaN,1,3.797842,NaN,1,0.116907,NaN,1,0.257966,NaN,1
19,rel_lion,0.0010,0.50,0.990,0.0100,3.839374,NaN,1,3.839374,NaN,1,3.837576,NaN,1,0.158203,NaN,1,0.275235,NaN,1

In [ ]:
rel_lion	0.0010	0.95	0.990	0.0100
rel_lion	0.0010	0.95	0.990	0.0010	3.300188
rel_lion	0.0010	0.95	0.990	0.0001	3.300793
rel_lion	0.0010	0.95	0.990	1.0000	3.317761

In [6]:
keep_opts = ["lion", "adamw", "rel_signum"]

mask = (
    summary["optimizer"].isin(keep_opts)
    | (
        (summary["optimizer"] == "rel_lion")
        & (summary["learning_rate"] == 0.001)
        & (summary["beta1"] == 0.95)
        & (summary["beta2"] == 0.99)
        & (summary["mass"].isin([0.01, 0.001, 0.0001, 1.0]))
    )
)

summary = summary.loc[mask].copy()

In [7]:
summary

,optimizer,learning_rate,beta1,beta2,mass,eval/best_val_loss_mean,eval/best_val_loss_std,eval/best_val_loss_count,eval/val_loss_mean,eval/val_loss_std,eval/val_loss_count,eval/train_loss_mean,eval/train_loss_std,eval/train_loss_count,train/max_grad_mean,train/max_grad_std,train/max_grad_count,train/grad_sparsity_mean,train/grad_sparsity_std,train/grad_sparsity_count
0,rel_lion,0.0010,0.95,0.99,0.0100,3.298597,NaN,1,3.298597,NaN,1,3.300747,NaN,1,0.064554,NaN,1,0.298314,NaN,1
1,rel_lion,0.0010,0.95,0.99,0.0010,3.300188,NaN,1,3.300188,NaN,1,3.302549,NaN,1,0.109107,NaN,1,0.303766,NaN,1
3,rel_lion,0.0010,0.95,0.99,0.0001,3.300793,NaN,1,3.300793,NaN,1,3.302801,NaN,1,0.162902,NaN,1,0.304657,NaN,1
6,lion,0.0010,0.90,0.99,0.1000,3.309639,NaN,1,3.309639,NaN,1,3.311647,NaN,1,0.022530,NaN,1,0.286176,NaN,1
8,adamw,0.0030,0.99,0.99,0.1000,3.317532,NaN,1,3.317532,NaN,1,3.320191,NaN,1,0.022705,NaN,1,0.276948,NaN,1
9,lion,0.0005,0.90,0.99,0.1000,3.317696,NaN,1,3.317696,NaN,1,3.319554,NaN,1,0.022575,NaN,1,0.281735,NaN,1
10,rel_lion,0.0010,0.95,0.99,1.0000,3.317761,NaN,1,3.317761,NaN,1,3.320150,NaN,1,0.039484,NaN,1,0.269874,NaN,1
14,rel_signum,0.0030,0.95,0.95,0.1000,3.343594,NaN,1,3.343594,NaN,1,3.346306,NaN,1,0.022361,NaN,1,0.273650,NaN,1
16,lion,0.0001,0.90,0.99,0.1000,3.353702,NaN,1,3.353702,NaN,1,3.355271,NaN,1,0.020142,NaN,1,0.273543,NaN,1

In [10]:
summary[['optimizer', 'learning_rate', 'beta1', 'beta2', 'mass', 'eval/best_val_loss_mean']]

     optimizer  learning_rate  beta1  beta2    mass  eval/best_val_loss_mean
0     rel_lion         0.0010   0.95   0.99  0.0100                 3.298597
1     rel_lion         0.0010   0.95   0.99  0.0010                 3.300188
3     rel_lion         0.0010   0.95   0.99  0.0001                 3.300793
6         lion         0.0010   0.90   0.99  0.1000                 3.309639
8        adamw         0.0030   0.99   0.99  0.1000                 3.317532
9         lion         0.0005   0.90   0.99  0.1000                 3.317696
10    rel_lion         0.0010   0.95   0.99  1.0000                 3.317761
14  rel_signum         0.0030   0.95   0.95  0.1000                 3.343594
16        lion         0.0001   0.90   0.99  0.1000                 3.353702